### ISSUE TITLE
le bloc "get .......... of motors ....." ne fonctionne pas avec le bloc "all motors"

### ISSUE THREAD

**Issue by show0k** [poppy-project/poppy-ergo-jr#23]

**Comment by show0k** [comment]
J'ai testé aussi avec un ancien fichier demo (où a fonctionnait avant) et ça ne fonctionne plus. 

peut-être que le problème ne vient pas des blocs mais d'autre chose ?

[--- Commented from Asana.com
#commenter Stephanie Noirpoudre
---[aa]

**Comment by show0k** [comment]
voir le sprite "poule"
avant ça fonctionnait

[--- Commented from Asana.com
#commenter Stephanie Noirpoudre
---[aa]

**Comment by show0k** [comment]
C'est simplement que je n'avais pas pushé la modif que j'avais fait. Encore un fois (oui, tu m'avais déjà posé cette question) s'il n'y a pas motor(s) c'est que ce n'était pas prévu d'avoir plusieurs moteurs. Il n'y a donc rien de cassé, juste une update que tu m'avais demandé qui n'a jaméis été envoyé dans la release officielle

[--- Commented from Asana.com
#commenter Théo Segonds
---[aa]

**Comment by pierre-rouanet** [comment]
Status update?

**Comment by pierre-rouanet** [comment]
Status update plz :)

**Comment by show0k** [comment]
Fixed https://github.com/poppy-project/pypot/blob/master/changelog.md#snap
