### ISSUE TITLE
Fichier STL non lisibles

### ISSUE THREAD

**Issue by Zagamort** [poppy-project/poppy-ergo-jr#35]
Bonjour,

Nous avons essayé de lire les fichiers STL de Popy ergo jr avec Cura, Makerbot, Meshmixer et Solidworks mais sans succès.
Les fichiers semblent invalides.

**Comment by show0k** [comment]
Hi,
It is an issue of the integration of git-lfs (used for tracking big STL files in the git repo) and github.com. "Source code".zip is automatically generated and didn"t download git-lfs tracked files...

You can download STL files with the [STL.zip](https://github.com/poppy-project/poppy-ergo-jr/releases/download/1.0.0-rc.2/STL.zip) directly in the release now.

**Comment by Zagamort** [comment]
Thanks, it's working fine now.
