### ISSUE TITLE
File size is truncated

### ISSUE THREAD

**Issue by cemox** [poppy-project/poppy-ergo-jr#52]
Hello, I cloned the project from two different operating systems (i,e, Ubuntu and OSX) and in each attempt the result was the same: files's are broken (file size is 132 bytes). So, I cannot open any of the files including the pdf files.

**Comment by show0k** [comment]
Hello,
It should be documented, but we are using [git-lfs ](https://git-lfs.github.com/) for storing bloat files (STL and PDF), if you don't have git-fs installed, you will only see them as a text files with a link.

**Comment by cemox** [comment]
thanks, I installed gif-los and everything is fine now
