### ISSUE TITLE
Face Tracking not working

### ISSUE THREAD

**Issue by vantony1** [poppy-project/poppy-ergo-jr#63]
Hello,

I am trying to use the face tracking primitive but its not working since the pi (booted with the ergo os image) seems to be missing a package that the camera/face-tracking relies on. We are unable to install the package using pip since the pi will only connect local networks and not the internet. (we tried playing around the the network settings but that broke the system and we have to re-burn the os image on the sd card)

Could you recommend what I do to access face tracking?

Best,

Victor

**Comment by ymollard** [comment]
Can you tell on which software version you experiment this issue (4.0.2 ? See in the up right corner of the window) and the code you use to showcase the problem?

**Comment by vantony1** [comment]
HI, thanks so much for getting back to me! I appreciate it

I am using v4.0.1

I finally figured out that my initial problem was with the camera I was using (for some reason it wasn't being detected by the pi). Now I'm using a usb camera which i getting detected by both the pi and the poppy code/api.

However, I am still not able to get the face tracking primitive to show up. I followed the instructions here to try to get it to show up: https://poppy.discourse.group/t/poppy-ergo-jr-face-tracking-configuration-bug/2642

But this didn't work for me. I tried to debug the issue by playing around with the shortcut_to_robot_init.py file and this is what I have come up with.

AttributeError: 'Robot' object has no attribute 'face_detector'

Could you let me know how I can get face tracking working? Its quite important for the project I am working on :)

Thanks again!

**Comment by vantony1** [comment]
Thank you so much! I got the primitive to work. I had to change both lines 52 and 55 along with adding the following lines to configuration/poppy_ergo_jr.json as mentioned in the forum post tagged earlier but under the sensors tag: 

"face_detector": {
      "type": "FaceDetector",
      "cameras": ["camera"],
      "freq": 1.0,
      "cascade": "/home/poppy/miniconda/share/OpenCV/haarcascades/haarcascade_frontalface_alt.xml",
      "need_robot" : true
    }

I hadn't put it under sensors before.

However, although the primitive is working -- its not functioning properly, i do not believe it is detecting or tracking the face. It just stays in the start position and has some occasional twitches. 

Do you have any reccomendations as to how I could debug this? A video of how face tracking primitive should look like would be immensely helpful as well.

The only thing I can thing that may be the cause of face tracking primitive not functioning as intended is that I am using a simply usb camera instead of a rpi camera. I know the camera is working though since I get a stream through the web viewer on poppy.local

Thank again for the help, I really appreciate it :)

**Comment by ymollard** [comment]
The "cascade" parameter here above is incorrect, it must be `/home/poppy/pyenv/lib/python3.7/site-packages/cv2/data/haarcascade_frontalface_alt.xml`

**Comment by ymollard** [comment]
Thank you for your feedback. The bug is fixed in 4.0.2 on PyPI [`poppy-ergo-jr`](https://pypi.org/project/poppy-ergo-jr/), and this is now a little bit documented here:
https://docs.poppy-project.org/en/programming/edit-robot-behaviour.html#add-a-sensor
